"""add spending plan part association to the transaction

Revision ID: 07ade4937244
Revises: 57e9918c7c5f
Create Date: 2020-12-27 18:40:37.148610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07ade4937244'
down_revision = '57e9918c7c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('spending_plan_part_id', sa.Integer(), nullable=False))
    op.drop_index('unique_transaction_index', table_name='transactions')
    op.create_index('unique_transaction_index', 'transactions', ['date', 'description', 'amount', 'account_id'], unique=True)
    op.create_foreign_key(None, 'transactions', 'spending_plan_parts', ['spending_plan_part_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index('unique_transaction_index', table_name='transactions')
    op.create_index('unique_transaction_index', 'transactions', ['date', 'description', 'amount'], unique=True)
    op.drop_column('transactions', 'spending_plan_part_id')
    # ### end Alembic commands ###
