"""add unique spending plan parts

Revision ID: 693c3a9e8811
Revises: fb1f8028c476
Create Date: 2020-12-22 16:22:43.128315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693c3a9e8811'
down_revision = 'fb1f8028c476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_plan_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('expected_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_spending_plan_parts_index', 'spending_plan_parts', ['category', 'label', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_spending_plan_parts_index', table_name='spending_plan_parts')
    op.drop_table('spending_plan_parts')
    # ### end Alembic commands ###
