"""remove uniqueness constraint on bank names

Revision ID: 57e9918c7c5f
Revises: 693c3a9e8811
Create Date: 2020-12-24 22:29:37.866242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e9918c7c5f'
down_revision = '693c3a9e8811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banks_name_key', 'banks', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('banks_name_key', 'banks', ['name'])
    # ### end Alembic commands ###
