"""add_unique_spending_plan_parts

Revision ID: 7e5a6ede14cc
Revises: 86ccb830a94f
Create Date: 2020-12-17 18:56:42.066131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5a6ede14cc'
down_revision = '86ccb830a94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_plan_parts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('expected_amount', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('unique_spending_plan_parts_index', 'spending_plan_parts', ['category', 'label', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_spending_plan_parts_index', table_name='spending_plan_parts')
    op.drop_table('spending_plan_parts')
    # ### end Alembic commands ###
