"""add_index_to_transactions

Revision ID: 1e33bd6fe8fc
Revises: ee139d47a7f5
Create Date: 2020-10-11 22:03:29.668911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e33bd6fe8fc'
down_revision = 'ee139d47a7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_transaction_index', 'transactions', ['date', 'description', 'amount'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_transaction_index', table_name='transactions')
    # ### end Alembic commands ###
