"""unique label user spending plan parts

Revision ID: b94523cd2d34
Revises: dcbc9ac03c92
Create Date: 2020-12-29 10:18:26.889923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b94523cd2d34'
down_revision = 'dcbc9ac03c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_spending_plan_parts_index', table_name='spending_plan_parts')
    op.create_index('unique_spending_plan_parts_index', 'spending_plan_parts', ['label', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_spending_plan_parts_index', table_name='spending_plan_parts')
    op.create_index('unique_spending_plan_parts_index', 'spending_plan_parts', ['category', 'label', 'user_id'], unique=True)
    # ### end Alembic commands ###
